language: node_js
node_js:
- 10.3.0
env:
  global:
    - GH_REF: github.com/roy-k/roy-k.github.io.git
    - secure: "11QR1BN2mPX2IyPxVEKAD3w+v6xEAWg6nuP1FElr+p7xL9mBxCT1JIFNJCttLRhTLOO9dfzcpb2evb00iYGucHAaO5mDAbrUXyvhbjFsgUn90jXc1VGVdXTP2bMD6ocAz5VnweUxYvKilL8ex+17MxPapg+dgCQ0ygKr4EYR3axOcCaGqPNWxHxuvhqeHEOWEzWkD9hJe7i/hKJLm6gAqtrw9gtOwVPkkRPaGD7El6mk+DWpQTIBvSBMaDYyhAHwZT7PmdxgXIJJ5Jqb6TKUwHNitvzIPwVXYbKsVE0j2RlznvP5KYo/5EbtKUhos+hQyiQsfdhlTm0h1j+I3nNCaMPK3uNRxgmJKTDtAS5U5l+vKhwB5aQBg6VS9BQ5g90b17w7MWZK22nQrug6bnZx1hUcZscjWCqz9OrIlHj10sJ9OuNZitdD4gv2tu/KqjOYI23TeZ0F9mHv7aeh80tlO/CHgcQdvR2TxtMYxeIxb3rAJecAhJdksyTAoP+pGm2rxaOtZzjp//G9Gl+yj15ARhJKOqz5me/DCxzlbV3poNfw8iCyDS+VGh8tyu7zEjPXl3X7KpxdOyIn+KzjOkhLwoAIaVtogYEBKV9TGesbEuVbyJyxjVqozUOzr368IM2Icm7O57CdyXbJvX5rR0dQlGp5TyACSAs6d923Yf1Y4K8="

install:
  - npm install
before_script:
  - npm install -g hexo
script:
  - hexo g
after_script:
  - cd public
  - git init
  - git config user.name "roy"
  - git config user.email "roy.k.gao@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
